---
include:
    - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_display
    - board: seeeduino_xiao_ble
    shield: totem_left
    - board: seeeduino_xiao_ble
    shield: totem_right
